### ISSUE TITLE
install-deps not working on Ubuntu?

### ISSUE THREAD

**Issue by redransil** [tkf/julia-venv#4]
tkf, thanks for doing this! It looks like it's going to be super useful.

I'm having issues with **julia-venv-manage install-deps**

All the install steps seem to work up until that point, and then I get an error:

File "myenv/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

I'm using Ubuntu 18.04.2, and have tried installing in both a conda environment and a virtualenv.

**julia-venv-manage show** gives:

No Conda/*/deps/build.log is found!
No PyCall/*/deps/build.log is found!
No PyCall/*/deps/deps.jl is found!

Any thoughts on what I should try next?

**Comment by tkf** [comment]
Ah, I think I only tested that command with Python 3.7.  But actually julia-venv is now obsolete.  I should update the README that you should use PyJulia directly now.

After I wrote julia-venv, I became a member of JuliaPy and integrated many improvements in PyJulia itself.  In current PyJulia `master`, I just implemented a similar but much more powerful solution https://github.com/JuliaPy/pyjulia/issues/185#issuecomment-482446645.
